# Generated by Django 3.2.9 on 2021-12-02 18:02

import bibliofund.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='bibliofund.category')),
            ],
            options={
                'verbose_name': 'Субкатегория',
                'verbose_name_plural': 'Субкатегории',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('abstract_ru', models.TextField(verbose_name='Аннотация на русском')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='Аннотация на английском')),
                ('slug', models.SlugField(max_length=300, null=True)),
                ('document_type', models.IntegerField(choices=[(0, 'Не выбран'), (1, 'Реферат'), (2, 'Дипломная работа'), (3, 'Магистерская диссертация'), (4, 'Отчет по практике'), (5, 'Курсовая работа'), (6, 'Курсовая практика'), (7, 'Практическая работа'), (8, 'Эссе'), (9, 'Доклад'), (10, 'Лекция'), (11, 'Методичка'), (12, 'Сочинение'), (13, 'Контрольная работа')], default=0, verbose_name='Тип')),
                ('file', models.FileField(upload_to=bibliofund.models.custom_upload_to, verbose_name='Файл')),
                ('file_format', models.CharField(blank=True, max_length=10, null=True, verbose_name='Формат файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliofund.category', verbose_name='')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['updated_at'],
            },
        ),
    ]
