# Generated by Django 3.2.9 on 2021-12-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.IntegerField(choices=[(0, 'Не выбран'), (1, 'Экономические'), (2, 'Гуманитарные'), (3, 'Юридические'), (4, 'Естественно-научные'), (5, 'Технические')], default=0, verbose_name='Тип категории'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bibliofund.category', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
