# Generated by Django 3.2.9 on 2021-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0002_auto_20211203_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'category_type')},
        ),
    ]
