# Generated by Django 4.0.2 on 2022-02-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0006_remove_document_old_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('view_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('like_count', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('dislike_count', models.IntegerField(default=0, verbose_name='Количество дизлайков')),
            ],
            options={
                'verbose_name': 'Стасистика',
                'verbose_name_plural': 'Статистики',
                'ordering': ['-view_count'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='statistic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliofund.filestatistic'),
        ),
    ]
