# Generated by Django 4.0.2 on 2022-02-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0007_filestatistic_document_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='statistic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliofund.filestatistic'),
        ),
    ]
