# Generated by Django 4.0.2 on 2022-02-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0008_alter_document_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestatistic',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='filestatistic',
            name='like_count',
        ),
    ]
