# Generated by Django 4.0.2 on 2022-03-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0010_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.IntegerField(choices=[(0, 'Не выбран'), (1, 'Реферат'), (2, 'Дипломная работа'), (3, 'Магистерская диссертация'), (4, 'Отчет по практике'), (5, 'Курсовая работа'), (6, 'Курсовая практика'), (7, 'Практическая работа'), (8, 'Эссе'), (9, 'Доклад'), (10, 'Лекция'), (11, 'Методические пособия'), (12, 'Сочинение'), (13, 'Контрольная работа')], default=0, verbose_name='Тип'),
        ),
    ]
