# Generated by Django 3.2.9 on 2021-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliofund', '0004_auto_20211203_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='old_file_format',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Старый формат файла'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
